Update connector with the new config update
CESARBR/knot-fog-connector-knot-cloud pull request #21
Opened 2020-09-11 16:08 UTC by Igoraamc

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:
         Update config event.

**Does this PR introduce any breaking changes?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] Related issues are referenced in the PR (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing
- [x] New/updated tests are included

**Testing environment:**

- Operating System/Platform: macOS Catalina
- Node version: v12.16.0
- Yarn version: 1.22.0

If you have relevant logs, error output and etc, please attach them.

**Other information:**

2020-09-14 15:29 UTC, esdrasjnr approved these changes
It looks great! 👍🏻 💯

2020-09-15 22:00 UTC, netoax requested changes
The main change you did in the commit _ccd560b1dd64d9ffeeeff4101aad325c552c6a9d_ was to remove the `updateSchema` operation, so its title should describe that.

Also, add a commit bumping this package version to `4.0.0` and update the CHANGELOG with the changes description.

2020-09-16 19:31 UTC, asf89 approved these changes

2020-09-17 01:29 UTC, netoax approved these changes
LGTM!

2020-09-17 01:29 UTC, merged